// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: proto/sgrh.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Tipos de Colaborador
type TipoColaborador int32

const (
	TipoColaborador_EFETIVO    TipoColaborador = 0
	TipoColaborador_AUTONOMO   TipoColaborador = 1
	TipoColaborador_ESTAGIARIO TipoColaborador = 2
)

// Enum value maps for TipoColaborador.
var (
	TipoColaborador_name = map[int32]string{
		0: "EFETIVO",
		1: "AUTONOMO",
		2: "ESTAGIARIO",
	}
	TipoColaborador_value = map[string]int32{
		"EFETIVO":    0,
		"AUTONOMO":   1,
		"ESTAGIARIO": 2,
	}
)

func (x TipoColaborador) Enum() *TipoColaborador {
	p := new(TipoColaborador)
	*p = x
	return p
}

func (x TipoColaborador) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TipoColaborador) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_sgrh_proto_enumTypes[0].Descriptor()
}

func (TipoColaborador) Type() protoreflect.EnumType {
	return &file_proto_sgrh_proto_enumTypes[0]
}

func (x TipoColaborador) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TipoColaborador.Descriptor instead.
func (TipoColaborador) EnumDescriptor() ([]byte, []int) {
	return file_proto_sgrh_proto_rawDescGZIP(), []int{0}
}

type Colaborador struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32           `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nome string          `protobuf:"bytes,2,opt,name=nome,proto3" json:"nome,omitempty"`
	Tipo TipoColaborador `protobuf:"varint,3,opt,name=tipo,proto3,enum=proto.TipoColaborador" json:"tipo,omitempty"`
	// Apenas um destes campos será preenchido, baseado no tipo
	//
	// Types that are assignable to DetalhesSalario:
	//	*Colaborador_SalarioMensal
	//	*Colaborador_Autonomo
	//	*Colaborador_AuxilioEstagio
	DetalhesSalario isColaborador_DetalhesSalario `protobuf_oneof:"detalhes_salario"`
}

func (x *Colaborador) Reset() {
	*x = Colaborador{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sgrh_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Colaborador) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Colaborador) ProtoMessage() {}

func (x *Colaborador) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sgrh_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Colaborador.ProtoReflect.Descriptor instead.
func (*Colaborador) Descriptor() ([]byte, []int) {
	return file_proto_sgrh_proto_rawDescGZIP(), []int{0}
}

func (x *Colaborador) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Colaborador) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *Colaborador) GetTipo() TipoColaborador {
	if x != nil {
		return x.Tipo
	}
	return TipoColaborador_EFETIVO
}

func (m *Colaborador) GetDetalhesSalario() isColaborador_DetalhesSalario {
	if m != nil {
		return m.DetalhesSalario
	}
	return nil
}

func (x *Colaborador) GetSalarioMensal() float64 {
	if x, ok := x.GetDetalhesSalario().(*Colaborador_SalarioMensal); ok {
		return x.SalarioMensal
	}
	return 0
}

func (x *Colaborador) GetAutonomo() *DetalhesAutonomo {
	if x, ok := x.GetDetalhesSalario().(*Colaborador_Autonomo); ok {
		return x.Autonomo
	}
	return nil
}

func (x *Colaborador) GetAuxilioEstagio() float64 {
	if x, ok := x.GetDetalhesSalario().(*Colaborador_AuxilioEstagio); ok {
		return x.AuxilioEstagio
	}
	return 0
}

type isColaborador_DetalhesSalario interface {
	isColaborador_DetalhesSalario()
}

type Colaborador_SalarioMensal struct {
	SalarioMensal float64 `protobuf:"fixed64,4,opt,name=salario_mensal,json=salarioMensal,proto3,oneof"` // Para Efetivo
}

type Colaborador_Autonomo struct {
	Autonomo *DetalhesAutonomo `protobuf:"bytes,5,opt,name=autonomo,proto3,oneof"` // Para Autonomo
}

type Colaborador_AuxilioEstagio struct {
	AuxilioEstagio float64 `protobuf:"fixed64,6,opt,name=auxilio_estagio,json=auxilioEstagio,proto3,oneof"` // Para Estagiario
}

func (*Colaborador_SalarioMensal) isColaborador_DetalhesSalario() {}

func (*Colaborador_Autonomo) isColaborador_DetalhesSalario() {}

func (*Colaborador_AuxilioEstagio) isColaborador_DetalhesSalario() {}

type DetalhesAutonomo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ValorHora        float64 `protobuf:"fixed64,1,opt,name=valor_hora,json=valorHora,proto3" json:"valor_hora,omitempty"`
	HorasTrabalhadas int32   `protobuf:"varint,2,opt,name=horas_trabalhadas,json=horasTrabalhadas,proto3" json:"horas_trabalhadas,omitempty"`
}

func (x *DetalhesAutonomo) Reset() {
	*x = DetalhesAutonomo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sgrh_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DetalhesAutonomo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetalhesAutonomo) ProtoMessage() {}

func (x *DetalhesAutonomo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sgrh_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetalhesAutonomo.ProtoReflect.Descriptor instead.
func (*DetalhesAutonomo) Descriptor() ([]byte, []int) {
	return file_proto_sgrh_proto_rawDescGZIP(), []int{1}
}

func (x *DetalhesAutonomo) GetValorHora() float64 {
	if x != nil {
		return x.ValorHora
	}
	return 0
}

func (x *DetalhesAutonomo) GetHorasTrabalhadas() int32 {
	if x != nil {
		return x.HorasTrabalhadas
	}
	return 0
}

type AddColaboradorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NomeDepartamento string       `protobuf:"bytes,1,opt,name=nome_departamento,json=nomeDepartamento,proto3" json:"nome_departamento,omitempty"`
	Colaborador      *Colaborador `protobuf:"bytes,2,opt,name=colaborador,proto3" json:"colaborador,omitempty"`
}

func (x *AddColaboradorRequest) Reset() {
	*x = AddColaboradorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sgrh_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddColaboradorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddColaboradorRequest) ProtoMessage() {}

func (x *AddColaboradorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sgrh_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddColaboradorRequest.ProtoReflect.Descriptor instead.
func (*AddColaboradorRequest) Descriptor() ([]byte, []int) {
	return file_proto_sgrh_proto_rawDescGZIP(), []int{2}
}

func (x *AddColaboradorRequest) GetNomeDepartamento() string {
	if x != nil {
		return x.NomeDepartamento
	}
	return ""
}

func (x *AddColaboradorRequest) GetColaborador() *Colaborador {
	if x != nil {
		return x.Colaborador
	}
	return nil
}

type DemitirColaboradorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NomeDepartamento string `protobuf:"bytes,1,opt,name=nome_departamento,json=nomeDepartamento,proto3" json:"nome_departamento,omitempty"`
	ColaboradorId    int32  `protobuf:"varint,2,opt,name=colaborador_id,json=colaboradorId,proto3" json:"colaborador_id,omitempty"`
}

func (x *DemitirColaboradorRequest) Reset() {
	*x = DemitirColaboradorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sgrh_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DemitirColaboradorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemitirColaboradorRequest) ProtoMessage() {}

func (x *DemitirColaboradorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sgrh_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemitirColaboradorRequest.ProtoReflect.Descriptor instead.
func (*DemitirColaboradorRequest) Descriptor() ([]byte, []int) {
	return file_proto_sgrh_proto_rawDescGZIP(), []int{3}
}

func (x *DemitirColaboradorRequest) GetNomeDepartamento() string {
	if x != nil {
		return x.NomeDepartamento
	}
	return ""
}

func (x *DemitirColaboradorRequest) GetColaboradorId() int32 {
	if x != nil {
		return x.ColaboradorId
	}
	return 0
}

type ListarColaboradoresRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NomeDepartamento string `protobuf:"bytes,1,opt,name=nome_departamento,json=nomeDepartamento,proto3" json:"nome_departamento,omitempty"`
}

func (x *ListarColaboradoresRequest) Reset() {
	*x = ListarColaboradoresRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sgrh_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListarColaboradoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListarColaboradoresRequest) ProtoMessage() {}

func (x *ListarColaboradoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sgrh_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListarColaboradoresRequest.ProtoReflect.Descriptor instead.
func (*ListarColaboradoresRequest) Descriptor() ([]byte, []int) {
	return file_proto_sgrh_proto_rawDescGZIP(), []int{4}
}

func (x *ListarColaboradoresRequest) GetNomeDepartamento() string {
	if x != nil {
		return x.NomeDepartamento
	}
	return ""
}

type ListarColaboradoresResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Colaboradores []*Colaborador `protobuf:"bytes,1,rep,name=colaboradores,proto3" json:"colaboradores,omitempty"`
}

func (x *ListarColaboradoresResponse) Reset() {
	*x = ListarColaboradoresResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sgrh_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListarColaboradoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListarColaboradoresResponse) ProtoMessage() {}

func (x *ListarColaboradoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sgrh_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListarColaboradoresResponse.ProtoReflect.Descriptor instead.
func (*ListarColaboradoresResponse) Descriptor() ([]byte, []int) {
	return file_proto_sgrh_proto_rawDescGZIP(), []int{5}
}

func (x *ListarColaboradoresResponse) GetColaboradores() []*Colaborador {
	if x != nil {
		return x.Colaboradores
	}
	return nil
}

type CalcularFolhaSalarialRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NomeDepartamento string `protobuf:"bytes,1,opt,name=nome_departamento,json=nomeDepartamento,proto3" json:"nome_departamento,omitempty"`
}

func (x *CalcularFolhaSalarialRequest) Reset() {
	*x = CalcularFolhaSalarialRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sgrh_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalcularFolhaSalarialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalcularFolhaSalarialRequest) ProtoMessage() {}

func (x *CalcularFolhaSalarialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sgrh_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalcularFolhaSalarialRequest.ProtoReflect.Descriptor instead.
func (*CalcularFolhaSalarialRequest) Descriptor() ([]byte, []int) {
	return file_proto_sgrh_proto_rawDescGZIP(), []int{6}
}

func (x *CalcularFolhaSalarialRequest) GetNomeDepartamento() string {
	if x != nil {
		return x.NomeDepartamento
	}
	return ""
}

type CalcularFolhaSalarialResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalFolha float64 `protobuf:"fixed64,1,opt,name=total_folha,json=totalFolha,proto3" json:"total_folha,omitempty"`
}

func (x *CalcularFolhaSalarialResponse) Reset() {
	*x = CalcularFolhaSalarialResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sgrh_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalcularFolhaSalarialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalcularFolhaSalarialResponse) ProtoMessage() {}

func (x *CalcularFolhaSalarialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sgrh_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalcularFolhaSalarialResponse.ProtoReflect.Descriptor instead.
func (*CalcularFolhaSalarialResponse) Descriptor() ([]byte, []int) {
	return file_proto_sgrh_proto_rawDescGZIP(), []int{7}
}

func (x *CalcularFolhaSalarialResponse) GetTotalFolha() float64 {
	if x != nil {
		return x.TotalFolha
	}
	return 0
}

// Resposta genérica para operações simples
type SGRHResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SGRHResponse) Reset() {
	*x = SGRHResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sgrh_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SGRHResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SGRHResponse) ProtoMessage() {}

func (x *SGRHResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sgrh_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SGRHResponse.ProtoReflect.Descriptor instead.
func (*SGRHResponse) Descriptor() ([]byte, []int) {
	return file_proto_sgrh_proto_rawDescGZIP(), []int{8}
}

func (x *SGRHResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SGRHResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_sgrh_proto protoreflect.FileDescriptor

var file_proto_sgrh_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x67, 0x72, 0x68, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xfc, 0x01, 0x0a, 0x0b, 0x43, 0x6f,
	0x6c, 0x61, 0x62, 0x6f, 0x72, 0x61, 0x64, 0x6f, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x6d, 0x65, 0x12, 0x2a, 0x0a,
	0x04, 0x74, 0x69, 0x70, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x69, 0x70, 0x6f, 0x43, 0x6f, 0x6c, 0x61, 0x62, 0x6f, 0x72, 0x61,
	0x64, 0x6f, 0x72, 0x52, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x12, 0x27, 0x0a, 0x0e, 0x73, 0x61, 0x6c,
	0x61, 0x72, 0x69, 0x6f, 0x5f, 0x6d, 0x65, 0x6e, 0x73, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x01, 0x48, 0x00, 0x52, 0x0d, 0x73, 0x61, 0x6c, 0x61, 0x72, 0x69, 0x6f, 0x4d, 0x65, 0x6e, 0x73,
	0x61, 0x6c, 0x12, 0x35, 0x0a, 0x08, 0x61, 0x75, 0x74, 0x6f, 0x6e, 0x6f, 0x6d, 0x6f, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x74,
	0x61, 0x6c, 0x68, 0x65, 0x73, 0x41, 0x75, 0x74, 0x6f, 0x6e, 0x6f, 0x6d, 0x6f, 0x48, 0x00, 0x52,
	0x08, 0x61, 0x75, 0x74, 0x6f, 0x6e, 0x6f, 0x6d, 0x6f, 0x12, 0x29, 0x0a, 0x0f, 0x61, 0x75, 0x78,
	0x69, 0x6c, 0x69, 0x6f, 0x5f, 0x65, 0x73, 0x74, 0x61, 0x67, 0x69, 0x6f, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x01, 0x48, 0x00, 0x52, 0x0e, 0x61, 0x75, 0x78, 0x69, 0x6c, 0x69, 0x6f, 0x45, 0x73, 0x74,
	0x61, 0x67, 0x69, 0x6f, 0x42, 0x12, 0x0a, 0x10, 0x64, 0x65, 0x74, 0x61, 0x6c, 0x68, 0x65, 0x73,
	0x5f, 0x73, 0x61, 0x6c, 0x61, 0x72, 0x69, 0x6f, 0x22, 0x5e, 0x0a, 0x10, 0x44, 0x65, 0x74, 0x61,
	0x6c, 0x68, 0x65, 0x73, 0x41, 0x75, 0x74, 0x6f, 0x6e, 0x6f, 0x6d, 0x6f, 0x12, 0x1d, 0x0a, 0x0a,
	0x76, 0x61, 0x6c, 0x6f, 0x72, 0x5f, 0x68, 0x6f, 0x72, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x09, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x48, 0x6f, 0x72, 0x61, 0x12, 0x2b, 0x0a, 0x11, 0x68,
	0x6f, 0x72, 0x61, 0x73, 0x5f, 0x74, 0x72, 0x61, 0x62, 0x61, 0x6c, 0x68, 0x61, 0x64, 0x61, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x68, 0x6f, 0x72, 0x61, 0x73, 0x54, 0x72, 0x61,
	0x62, 0x61, 0x6c, 0x68, 0x61, 0x64, 0x61, 0x73, 0x22, 0x7a, 0x0a, 0x15, 0x41, 0x64, 0x64, 0x43,
	0x6f, 0x6c, 0x61, 0x62, 0x6f, 0x72, 0x61, 0x64, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x2b, 0x0a, 0x11, 0x6e, 0x6f, 0x6d, 0x65, 0x5f, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74,
	0x61, 0x6d, 0x65, 0x6e, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x6e, 0x6f,
	0x6d, 0x65, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x6f, 0x12, 0x34,
	0x0a, 0x0b, 0x63, 0x6f, 0x6c, 0x61, 0x62, 0x6f, 0x72, 0x61, 0x64, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6c, 0x61,
	0x62, 0x6f, 0x72, 0x61, 0x64, 0x6f, 0x72, 0x52, 0x0b, 0x63, 0x6f, 0x6c, 0x61, 0x62, 0x6f, 0x72,
	0x61, 0x64, 0x6f, 0x72, 0x22, 0x6f, 0x0a, 0x19, 0x44, 0x65, 0x6d, 0x69, 0x74, 0x69, 0x72, 0x43,
	0x6f, 0x6c, 0x61, 0x62, 0x6f, 0x72, 0x61, 0x64, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x2b, 0x0a, 0x11, 0x6e, 0x6f, 0x6d, 0x65, 0x5f, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74,
	0x61, 0x6d, 0x65, 0x6e, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x6e, 0x6f,
	0x6d, 0x65, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x6f, 0x12, 0x25,
	0x0a, 0x0e, 0x63, 0x6f, 0x6c, 0x61, 0x62, 0x6f, 0x72, 0x61, 0x64, 0x6f, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x63, 0x6f, 0x6c, 0x61, 0x62, 0x6f, 0x72, 0x61,
	0x64, 0x6f, 0x72, 0x49, 0x64, 0x22, 0x49, 0x0a, 0x1a, 0x4c, 0x69, 0x73, 0x74, 0x61, 0x72, 0x43,
	0x6f, 0x6c, 0x61, 0x62, 0x6f, 0x72, 0x61, 0x64, 0x6f, 0x72, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x11, 0x6e, 0x6f, 0x6d, 0x65, 0x5f, 0x64, 0x65, 0x70, 0x61,
	0x72, 0x74, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10,
	0x6e, 0x6f, 0x6d, 0x65, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x6f,
	0x22, 0x57, 0x0a, 0x1b, 0x4c, 0x69, 0x73, 0x74, 0x61, 0x72, 0x43, 0x6f, 0x6c, 0x61, 0x62, 0x6f,
	0x72, 0x61, 0x64, 0x6f, 0x72, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x38, 0x0a, 0x0d, 0x63, 0x6f, 0x6c, 0x61, 0x62, 0x6f, 0x72, 0x61, 0x64, 0x6f, 0x72, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43,
	0x6f, 0x6c, 0x61, 0x62, 0x6f, 0x72, 0x61, 0x64, 0x6f, 0x72, 0x52, 0x0d, 0x63, 0x6f, 0x6c, 0x61,
	0x62, 0x6f, 0x72, 0x61, 0x64, 0x6f, 0x72, 0x65, 0x73, 0x22, 0x4b, 0x0a, 0x1c, 0x43, 0x61, 0x6c,
	0x63, 0x75, 0x6c, 0x61, 0x72, 0x46, 0x6f, 0x6c, 0x68, 0x61, 0x53, 0x61, 0x6c, 0x61, 0x72, 0x69,
	0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x11, 0x6e, 0x6f, 0x6d,
	0x65, 0x5f, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x6e, 0x6f, 0x6d, 0x65, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74,
	0x61, 0x6d, 0x65, 0x6e, 0x74, 0x6f, 0x22, 0x40, 0x0a, 0x1d, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c,
	0x61, 0x72, 0x46, 0x6f, 0x6c, 0x68, 0x61, 0x53, 0x61, 0x6c, 0x61, 0x72, 0x69, 0x61, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x5f, 0x66, 0x6f, 0x6c, 0x68, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x46, 0x6f, 0x6c, 0x68, 0x61, 0x22, 0x42, 0x0a, 0x0c, 0x53, 0x47, 0x52, 0x48,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a, 0x3c, 0x0a, 0x0f,
	0x54, 0x69, 0x70, 0x6f, 0x43, 0x6f, 0x6c, 0x61, 0x62, 0x6f, 0x72, 0x61, 0x64, 0x6f, 0x72, 0x12,
	0x0b, 0x0a, 0x07, 0x45, 0x46, 0x45, 0x54, 0x49, 0x56, 0x4f, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08,
	0x41, 0x55, 0x54, 0x4f, 0x4e, 0x4f, 0x4d, 0x4f, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x45, 0x53,
	0x54, 0x41, 0x47, 0x49, 0x41, 0x52, 0x49, 0x4f, 0x10, 0x02, 0x32, 0xe8, 0x02, 0x0a, 0x04, 0x53,
	0x47, 0x52, 0x48, 0x12, 0x4b, 0x0a, 0x14, 0x41, 0x64, 0x69, 0x63, 0x69, 0x6f, 0x6e, 0x61, 0x72,
	0x43, 0x6f, 0x6c, 0x61, 0x62, 0x6f, 0x72, 0x61, 0x64, 0x6f, 0x72, 0x12, 0x1c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x64, 0x64, 0x43, 0x6f, 0x6c, 0x61, 0x62, 0x6f, 0x72, 0x61, 0x64,
	0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x53, 0x47, 0x52, 0x48, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x4d, 0x0a, 0x12, 0x44, 0x65, 0x6d, 0x69, 0x74, 0x69, 0x72, 0x43, 0x6f, 0x6c, 0x61, 0x62,
	0x6f, 0x72, 0x61, 0x64, 0x6f, 0x72, 0x12, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44,
	0x65, 0x6d, 0x69, 0x74, 0x69, 0x72, 0x43, 0x6f, 0x6c, 0x61, 0x62, 0x6f, 0x72, 0x61, 0x64, 0x6f,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x53, 0x47, 0x52, 0x48, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x5e, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x61, 0x72, 0x43, 0x6f, 0x6c, 0x61, 0x62, 0x6f, 0x72,
	0x61, 0x64, 0x6f, 0x72, 0x65, 0x73, 0x12, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x61, 0x72, 0x43, 0x6f, 0x6c, 0x61, 0x62, 0x6f, 0x72, 0x61, 0x64, 0x6f, 0x72,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x61, 0x72, 0x43, 0x6f, 0x6c, 0x61, 0x62, 0x6f, 0x72, 0x61,
	0x64, 0x6f, 0x72, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x64, 0x0a, 0x15, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x72, 0x46, 0x6f, 0x6c, 0x68, 0x61,
	0x53, 0x61, 0x6c, 0x61, 0x72, 0x69, 0x61, 0x6c, 0x12, 0x23, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x72, 0x46, 0x6f, 0x6c, 0x68, 0x61, 0x53, 0x61,
	0x6c, 0x61, 0x72, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x72, 0x46, 0x6f,
	0x6c, 0x68, 0x61, 0x53, 0x61, 0x6c, 0x61, 0x72, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x53, 0x47, 0x52, 0x48, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_sgrh_proto_rawDescOnce sync.Once
	file_proto_sgrh_proto_rawDescData = file_proto_sgrh_proto_rawDesc
)

func file_proto_sgrh_proto_rawDescGZIP() []byte {
	file_proto_sgrh_proto_rawDescOnce.Do(func() {
		file_proto_sgrh_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_sgrh_proto_rawDescData)
	})
	return file_proto_sgrh_proto_rawDescData
}

var file_proto_sgrh_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_sgrh_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_sgrh_proto_goTypes = []interface{}{
	(TipoColaborador)(0),                  // 0: proto.TipoColaborador
	(*Colaborador)(nil),                   // 1: proto.Colaborador
	(*DetalhesAutonomo)(nil),              // 2: proto.DetalhesAutonomo
	(*AddColaboradorRequest)(nil),         // 3: proto.AddColaboradorRequest
	(*DemitirColaboradorRequest)(nil),     // 4: proto.DemitirColaboradorRequest
	(*ListarColaboradoresRequest)(nil),    // 5: proto.ListarColaboradoresRequest
	(*ListarColaboradoresResponse)(nil),   // 6: proto.ListarColaboradoresResponse
	(*CalcularFolhaSalarialRequest)(nil),  // 7: proto.CalcularFolhaSalarialRequest
	(*CalcularFolhaSalarialResponse)(nil), // 8: proto.CalcularFolhaSalarialResponse
	(*SGRHResponse)(nil),                  // 9: proto.SGRHResponse
}
var file_proto_sgrh_proto_depIdxs = []int32{
	0, // 0: proto.Colaborador.tipo:type_name -> proto.TipoColaborador
	2, // 1: proto.Colaborador.autonomo:type_name -> proto.DetalhesAutonomo
	1, // 2: proto.AddColaboradorRequest.colaborador:type_name -> proto.Colaborador
	1, // 3: proto.ListarColaboradoresResponse.colaboradores:type_name -> proto.Colaborador
	3, // 4: proto.SGRH.AdicionarColaborador:input_type -> proto.AddColaboradorRequest
	4, // 5: proto.SGRH.DemitirColaborador:input_type -> proto.DemitirColaboradorRequest
	5, // 6: proto.SGRH.ListarColaboradores:input_type -> proto.ListarColaboradoresRequest
	7, // 7: proto.SGRH.CalcularFolhaSalarial:input_type -> proto.CalcularFolhaSalarialRequest
	9, // 8: proto.SGRH.AdicionarColaborador:output_type -> proto.SGRHResponse
	9, // 9: proto.SGRH.DemitirColaborador:output_type -> proto.SGRHResponse
	6, // 10: proto.SGRH.ListarColaboradores:output_type -> proto.ListarColaboradoresResponse
	8, // 11: proto.SGRH.CalcularFolhaSalarial:output_type -> proto.CalcularFolhaSalarialResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_sgrh_proto_init() }
func file_proto_sgrh_proto_init() {
	if File_proto_sgrh_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_sgrh_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Colaborador); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sgrh_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DetalhesAutonomo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sgrh_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddColaboradorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sgrh_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DemitirColaboradorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sgrh_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListarColaboradoresRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sgrh_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListarColaboradoresResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sgrh_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalcularFolhaSalarialRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sgrh_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalcularFolhaSalarialResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sgrh_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SGRHResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_sgrh_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Colaborador_SalarioMensal)(nil),
		(*Colaborador_Autonomo)(nil),
		(*Colaborador_AuxilioEstagio)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_sgrh_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sgrh_proto_goTypes,
		DependencyIndexes: file_proto_sgrh_proto_depIdxs,
		EnumInfos:         file_proto_sgrh_proto_enumTypes,
		MessageInfos:      file_proto_sgrh_proto_msgTypes,
	}.Build()
	File_proto_sgrh_proto = out.File
	file_proto_sgrh_proto_rawDesc = nil
	file_proto_sgrh_proto_goTypes = nil
	file_proto_sgrh_proto_depIdxs = nil
}
